{"uid":"1f8df4e85985b47f","name":"test_send_message","fullName":"tests.test_example.ExampleTestCase#test_send_message","historyId":"3bc4f3765c9b31fcf733254dd25c049d","time":{"start":1755771815753,"stop":1755771816364,"duration":611},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.127)\nStacktrace:\n#0 0x562579e1501a <unknown>\n#1 0x5625798b4a70 <unknown>\n#2 0x5625798abcf1 <unknown>\n#3 0x56257989d099 <unknown>\n#4 0x56257989ede0 <unknown>\n#5 0x56257989d43e <unknown>\n#6 0x56257989cdaa <unknown>\n#7 0x56257989ca85 <unknown>\n#8 0x56257989a8ee <unknown>\n#9 0x56257989b0ca <unknown>\n#10 0x5625798b7f99 <unknown>\n#11 0x562579952d65 <unknown>\n#12 0x56257992c3e2 <unknown>\n#13 0x56257995214f <unknown>\n#14 0x56257992c1b3 <unknown>\n#15 0x5625798f859b <unknown>\n#16 0x5625798f9971 <unknown>\n#17 0x562579dda1eb <unknown>\n#18 0x562579dddf39 <unknown>\n#19 0x562579dc12c9 <unknown>\n#20 0x562579ddeae8 <unknown>\n#21 0x562579da5baf <unknown>\n#22 0x562579e020a8 <unknown>\n#23 0x562579e02286 <unknown>\n#24 0x562579e13ff6 <unknown>\n#25 0x7f7d5149caa4 <unknown>\n#26 0x7f7d51529c3c <unknown>","statusTrace":"self = <test_example.ExampleTestCase testMethod=test_send_message>\n\n    def test_send_message(self):\n>       self.home.open(OLLAMA_URL)\n\ntests/test_example.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/home_page.py:21: in open\n    self.driver.get(url)\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb6f781f750>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#24 0x562579e13ff6 \\\\u003Cunknown>\\\\n#25 0x7f7d5149caa4 \\\\u003Cunknown>\\\\n#26 0x7f7d51529c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=139.0.7258.127)\nE       Stacktrace:\nE       #0 0x562579e1501a <unknown>\nE       #1 0x5625798b4a70 <unknown>\nE       #2 0x5625798abcf1 <unknown>\nE       #3 0x56257989d099 <unknown>\nE       #4 0x56257989ede0 <unknown>\nE       #5 0x56257989d43e <unknown>\nE       #6 0x56257989cdaa <unknown>\nE       #7 0x56257989ca85 <unknown>\nE       #8 0x56257989a8ee <unknown>\nE       #9 0x56257989b0ca <unknown>\nE       #10 0x5625798b7f99 <unknown>\nE       #11 0x562579952d65 <unknown>\nE       #12 0x56257992c3e2 <unknown>\nE       #13 0x56257995214f <unknown>\nE       #14 0x56257992c1b3 <unknown>\nE       #15 0x5625798f859b <unknown>\nE       #16 0x5625798f9971 <unknown>\nE       #17 0x562579dda1eb <unknown>\nE       #18 0x562579dddf39 <unknown>\nE       #19 0x562579dc12c9 <unknown>\nE       #20 0x562579ddeae8 <unknown>\nE       #21 0x562579da5baf <unknown>\nE       #22 0x562579e020a8 <unknown>\nE       #23 0x562579e02286 <unknown>\nE       #24 0x562579e13ff6 <unknown>\nE       #25 0x7f7d5149caa4 <unknown>\nE       #26 0x7f7d51529c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase","time":{"start":1755771796646,"stop":1755771796646,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase::0","time":{"start":1755771816387,"stop":1755771816387,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_example"},{"name":"subSuite","value":"ExampleTestCase"},{"name":"host","value":"pkrvmqc4gcfdwos"},{"name":"thread","value":"2495-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_example"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"4fdd5228dd5f660e","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//34.245.153.13%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2034.245.153.13%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1755771808883,"stop":1755771811157,"duration":2274}},{"uid":"5ca44d038f1fd909","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//34.245.153.13%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2034.245.153.13%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1755771807471,"stop":1755771810150,"duration":2679}},{"uid":"6184c53ecefe3f03","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.127)\nStacktrace:\n#0 0x55886c17601a <unknown>\n#1 0x55886bc15a70 <unknown>\n#2 0x55886bc0ccf1 <unknown>\n#3 0x55886bbfe099 <unknown>\n#4 0x55886bbffde0 <unknown>\n#5 0x55886bbfe43e <unknown>\n#6 0x55886bbfddaa <unknown>\n#7 0x55886bbfda85 <unknown>\n#8 0x55886bbfb8ee <unknown>\n#9 0x55886bbfc0ca <unknown>\n#10 0x55886bc18f99 <unknown>\n#11 0x55886bcb3d65 <unknown>\n#12 0x55886bc8d3e2 <unknown>\n#13 0x55886bcb314f <unknown>\n#14 0x55886bc8d1b3 <unknown>\n#15 0x55886bc5959b <unknown>\n#16 0x55886bc5a971 <unknown>\n#17 0x55886c13b1eb <unknown>\n#18 0x55886c13ef39 <unknown>\n#19 0x55886c1222c9 <unknown>\n#20 0x55886c13fae8 <unknown>\n#21 0x55886c106baf <unknown>\n#22 0x55886c1630a8 <unknown>\n#23 0x55886c163286 <unknown>\n#24 0x55886c174ff6 <unknown>\n#25 0x7f933d29caa4 <unknown>\n#26 0x7f933d329c3c <unknown>","time":{"start":1755771806203,"stop":1755771807023,"duration":820}},{"uid":"491e1c0c6a8d0c00","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.127)\nStacktrace:\n#0 0x55f004cec01a <unknown>\n#1 0x55f00478ba70 <unknown>\n#2 0x55f004782cf1 <unknown>\n#3 0x55f004774099 <unknown>\n#4 0x55f004775de0 <unknown>\n#5 0x55f00477443e <unknown>\n#6 0x55f004773daa <unknown>\n#7 0x55f004773a85 <unknown>\n#8 0x55f0047718ee <unknown>\n#9 0x55f0047720ca <unknown>\n#10 0x55f00478ef99 <unknown>\n#11 0x55f004829d65 <unknown>\n#12 0x55f0048033e2 <unknown>\n#13 0x55f00482914f <unknown>\n#14 0x55f0048031b3 <unknown>\n#15 0x55f0047cf59b <unknown>\n#16 0x55f0047d0971 <unknown>\n#17 0x55f004cb11eb <unknown>\n#18 0x55f004cb4f39 <unknown>\n#19 0x55f004c982c9 <unknown>\n#20 0x55f004cb5ae8 <unknown>\n#21 0x55f004c7cbaf <unknown>\n#22 0x55f004cd90a8 <unknown>\n#23 0x55f004cd9286 <unknown>\n#24 0x55f004ceaff6 <unknown>\n#25 0x7ff0b4c9caa4 <unknown>\n#26 0x7ff0b4d29c3c <unknown>","time":{"start":1755771805357,"stop":1755771806161,"duration":804}},{"uid":"d01e64452374f241","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//34.245.153.13%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2034.245.153.13%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1755771803842,"stop":1755771805980,"duration":2138}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"1f8df4e85985b47f.json","parameterValues":[]}